source 'https://rubygems.org'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'rails', github: 'rails/rails', branch: '4-2-stable'
gem 'sass-rails', '4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'eventmachine'
group :test, :development do
  gem "rspec-rails"
  gem "capybara"
  gem "launchy"
  gem "rack_session_access"
  gem "selenium-webdriver"
  gem "better_errors"
  gem "binding_of_caller"
  gem "factory_bot_rails"
  gem "simplecov"
  # gem "database_cleaner", "~> 1.6.2"
  gem "sqlite3"
  gem "pry"
  gem "guard-rspec", require: false
  gem "thin"
end

gem "bootstrap-sass", "~> 3.1.1"
gem "faker"
gem "friendly_id"
